import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { createCatalog, MemoryCacheStore } from "../src/index.js";
import { createSmallWindowRuntime, queryCompositionRankings, handleCompDetailRequest } from "../src/app/small-window-server.js";
import { createTftToolHandlers } from "../src/domain/tft/tool-handler-factory.js";
import { ToolRegistry } from "../src/agent/tools/registry.js";
import { createStructuredToolDefinitions } from "../src/agent/tools/definitions.js";
import { EvidenceLedger } from "../src/react/evidence-ledger.js";
import { SkillRegistry, UNIT_PLAY_GUIDANCE_SKILL as skill, matchSkill } from "../src/skills/index.js";
import { analyzeUnitPlaySkillEvidence } from "../src/domain/tft/unit-play-skill-evidence.js";
import { UNIT_PLAY_GUIDANCE_SKILL_V1_4 as candidateSkill } from "../src/skills/definitions/unit-play-guidance.js";
import { UNIT_PLAY_GUIDANCE_SKILL_V1_5 as mechanismSkill, UNIT_PLAY_GUIDANCE_SKILL_V1_5_3 as answerSkill, UNIT_PLAY_GUIDANCE_SKILL_V1_5_4 as compactAnswerSkill, UNIT_PLAY_GUIDANCE_SKILL_V1_5_5 as cardsOnlyAnswerSkill, UNIT_PLAY_GUIDANCE_SKILL_V1_5_6 as exactCardQuerySkill, UNIT_PLAY_GUIDANCE_SKILL_V1_5_7 as batchMechanismSkill } from "../src/skills/definitions/unit-play-guidance.js";
import { buildOfficialTftItemDetailsCatalog } from "../src/data/official-item-details.js";
import { createLegacySeasonFixture } from "./fixtures/season-context.js";

const NOW = Date.parse("2026-08-30T08:00:00Z");
const stamp = new Date(NOW).toISOString();
const registry = new ToolRegistry(createStructuredToolDefinitions());
const raw = JSON.parse(await readFile(new URL("./fixtures/comp-rankings/metatft-comps-page-minimal.json", import.meta.url), "utf8"));
// These are generated by production adapters from existing offline provider
// fixtures. Source time is advanced for freshness tests; no live data is fetched.
const names = [...new Set(Object.values(raw.compsData.results.data.cluster_details).flatMap((row) => row.units_string.split(",").map((name) => name.trim())))];
const catalog = createCatalog({ units: names.map((apiName) => ({ apiName, zhName: apiName, name: apiName, traits: [] })), items: [], traits: [] });
const season = { id: "set17-live", currentPatch: "17.9", environment: "live", source: { queue: "1100" } };
const compsData = structuredClone(raw.compsData);
const compsStats = structuredClone(raw.compsStats);
compsData.updated = NOW;
compsStats.updated = NOW;
const rankings = await queryCompositionRankings({ limit: 5 }, catalog, {
  compsClient: { getCompsData: async () => compsData, getCompsStats: async () => compsStats }
}, { seasonContext: season, details: { units: new Map() } });
const plan = rankings.results[0].tacticalDetailQueryPlan;
const unitId = plan.units[0];
const detailRuntime = createSmallWindowRuntime({ cacheStore: new MemoryCacheStore(), catalog,
  seasonContextService: createLegacySeasonFixture(),
  compsClient: {
    getCompDetails: async () => ({ updated: NOW, results: { positioning: { units: Object.fromEntries(plan.units.map((apiName, index) => [apiName, { positions: [{ cell: index + 1, count: 10 }] }])) } } }),
    getCompAugmentTiers: async () => ({ updated: NOW, results: {} })
  }
});
const detail = { ...await handleCompDetailRequest({ compId: plan.compositionId, clusterId: plan.clusterId, units: plan.units, seasonContextId: season.id }, detailRuntime),
  type: "composition_tactical_details", compositionRef: { compId: plan.compositionId, clusterId: plan.clusterId } };
const semantic = await createTftToolHandlers({ registry, seasonContext: season, knowledgeSearch: async () => [{
  id: "knowledge-role", documentType: "mechanism_knowledge", claimType: "mechanism", claim: `${unitId}是输出英雄。`, patch: "17.9", updatedAt: stamp
}] }).handlers.semantic_search({ query: `${unitId}定位` });

function fixture() {
  let next = 0;
  const ledger = new EvidenceLedger({ createId: () => `fixture-${++next}`, now: () => NOW });
  const result = { status: "completed", evidence: [], observations: [], evidenceIds: [], answer: "" };
  const add = (toolName, value) => {
    const definition = registry.get(toolName);
    const toolResult = { toolName, toolCallId: `call-${next}`, status: "completed", value,
      metadata: { source: definition.source, evidenceType: definition.evidenceType, updatedAt: value.updatedAt ?? value.source?.updatedAt, modelGeneratedStatistics: false } };
    const { entry } = ledger.add({ definition, toolResult, evidenceContract: { source: definition.source, type: definition.evidenceType, requiredFields: ["source", "updatedAt"], allowModelGeneratedStatistics: false } });
    assert.ok(entry, toolName);
    result.observations.push({ type: "tool_result", tool: toolName, status: "completed", toolCallId: entry.toolCallId, evidenceId: entry.evidenceId, evidenceStatus: "valid", value });
  };
  add("comps_rankings", rankings);
  add("composition_tactical_details", detail);
  add("unit_builds", { type: "unit_build_rankings", unit: { apiName: unitId, name: unitId },
    query: { unit: unitId, seasonContextId: season.id, patch: "17.9" },
    cards: [{ items: [{ apiName: "TFT_Item_InfinityEdge", name: "无尽之刃" }], stats: { games: 100 } }], source: { provider: "metatft", updatedAt: stamp } });
  add("semantic_search", semantic);
  result.evidence = ledger.snapshot().entries;
  result.evidenceIds = result.evidence.map(({ evidenceId }) => evidenceId);
  const taskFrame = { schemaVersion: "task-frame.v1", domain: "tft", action: "recommend", goal: "recommend_unit_play",
    expectedOutput: ["unit_play_guidance"], understandingStatus: "understood_and_supported", ambiguities: [],
    subjects: [{ expectedType: "champion", resolvedId: unitId }] };
  const selection = matchSkill(taskFrame, new SkillRegistry({ definitions: [skill], toolRegistry: registry }));
  return { skill, taskFrame, selection, runtimeAvailableTools: skill.allowedTools, toolRegistry: registry,
    scope: { unitId, seasonContextId: season.id, patch: "17.9" }, result, now: NOW };
}

test("production ranking and positioning adapters yield bounded, deterministic current facets", () => {
  const input = fixture();
  const before = JSON.stringify(input.result);
  const report = analyzeUnitPlaySkillEvidence(input);
  assert.deepEqual(report.coveredFacets, ["composition_context", "positioning"], JSON.stringify(report));
  assert.equal(report.equipmentStatisticsObserved, true);
  assert.deepEqual(report.missingFacets, ["unit_role", "equipment_logic"]);
  assert.equal(report.completionProjectionStatus, "rejected");
  assert.equal(report.answerCoverage.completionEvaluated, false);
  assert.deepEqual(report, analyzeUnitPlaySkillEvidence(input));
  assert.equal(JSON.stringify(input.result), before);
});

test("free semantic text and composition membership cannot become role or timing facts", () => {
  const report = analyzeUnitPlaySkillEvidence(fixture());
  assert.equal(report.diagnosticCounts.semantic_facet_binding_unavailable, 1);
  assert.ok(!report.coveredFacets.includes("unit_role"));
  assert.ok(!report.sourceStatements.some(({ facetId }) => facetId === "when_to_play"));
});

test("source statements are accepted in Chinese and English only with actual citations", () => {
  for (const localeIndex of [0, 1]) {
    const input = fixture();
    const first = analyzeUnitPlaySkillEvidence(input);
    input.result.answer = first.sourceStatements.map(({ sentences }) => sentences[localeIndex]).join("\n");
    assert.deepEqual(analyzeUnitPlaySkillEvidence(input).answerCoverage.verifiedFacets, ["composition_context", "positioning"]);
    input.result.evidenceIds = [];
    assert.deepEqual(analyzeUnitPlaySkillEvidence(input).answerCoverage.verifiedFacets, []);
  }
});

test("keywords, negated source statements, fabricated roles and paraphrases remain unassessed", () => {
  const input = fixture();
  const statement = analyzeUnitPlaySkillEvidence(input).sourceStatements[0].sentences[0];
  for (const answer of ["定位 装备 阵容 站位", `并非${statement}`, `${unitId}是主C，因为他是阵容成员。`, "这名英雄应该摆在后排。"] ) {
    input.result.answer = answer;
    assert.deepEqual(analyzeUnitPlaySkillEvidence(input).answerCoverage.verifiedFacets, []);
  }
});

test("mismatched seasons, patches and champions cannot supply current coverage", () => {
  for (const scope of [{ seasonContextId: "set18-live" }, { patch: "17.8" }, { unitId: "TFT17_Other" }]) {
    const input = fixture();
    input.scope = { ...input.scope, ...scope };
    const report = analyzeUnitPlaySkillEvidence(input);
    assert.deepEqual(report.coveredFacets, []);
    assert.equal(report.equipmentStatisticsObserved, false);
  }
});

test("historical, stale, future-dated and missing-time entries cannot be promoted", () => {
  for (const mutate of [
    (entry) => { entry.temporalStatus = "historical"; },
    (entry) => { entry.metadata.cache = { stale: true }; },
    (entry) => { entry.metadata.updatedAt = "2026-08-31T00:00:00Z"; },
    (entry) => { entry.updatedAt = "2026-08-29T00:00:00Z"; },
    (entry) => { entry.metadata.updatedAt = null; }
  ]) {
    const input = fixture();
    input.result.evidence.forEach(mutate);
    const report = analyzeUnitPlaySkillEvidence(input);
    assert.deepEqual(report.coveredFacets, []);
    assert.equal(report.equipmentStatisticsObserved, false);
  }
});

test("a stale positioning source cannot borrow a fresh outer timestamp", () => {
  const input = fixture();
  input.result.evidence.find(({ toolName }) => toolName === "composition_tactical_details").value.formation.source.updatedAt = "2026-08-29T00:00:00Z";
  assert.ok(!analyzeUnitPlaySkillEvidence(input).coveredFacets.includes("positioning"));
});

test("positioning requires a matching source plan, cluster, complete roster and translated cell", () => {
  for (const mutate of [
    (value) => { value.clusterId = "other"; },
    (value) => { value.compId = "other"; },
    (value) => { value.formation.units.pop(); },
    (value) => { value.formation.units[0].boardPosition = null; },
    (value) => { value.formation.units[0].boardPosition.rowFromFront = 9; },
    (value) => { value.formation.units[0].boardPosition.rowFromFront = 1; },
    (value) => { delete value.formation.source.updatedAt; },
    (value) => { value.formation.units.push(value.formation.units[0]); },
    (value) => { value.formation.source.endpoint = "/other"; }
  ]) {
    const input = fixture();
    mutate(input.result.evidence.find(({ toolName }) => toolName === "composition_tactical_details").value);
    assert.ok(!analyzeUnitPlaySkillEvidence(input).coveredFacets.includes("positioning"));
  }
});

test("ambiguous compositions and unverified Ledger entries cannot support facets", () => {
  const input = fixture();
  input.result.evidence[0].value.resolution.status = "ambiguous";
  assert.deepEqual(analyzeUnitPlaySkillEvidence(input).coveredFacets, []);
  for (const mutate of [
    (candidate) => { candidate.result.observations = []; },
    (candidate) => { candidate.result.evidence.forEach((entry) => { entry.metadata.source = "unregistered"; }); },
    (candidate) => { candidate.runtimeAvailableTools = []; }
  ]) {
    const candidate = fixture();
    mutate(candidate);
    assert.deepEqual(analyzeUnitPlaySkillEvidence(candidate).coveredFacets, []);
  }
});

test("tool failures and empty observations remain missing, not fabricated absence", () => {
  const input = fixture();
  input.result.evidence = [];
  input.result.observations = [{ type: "tool_failed", tool: "unit_builds", error: { message: "secret raw error must not escape" } }];
  const report = analyzeUnitPlaySkillEvidence(input);
  assert.equal(report.dataAvailability.current_unit_build_statistics, "unknown");
  assert.equal(report.availabilityReasons.current_unit_build_statistics, "source_failed");
  assert.equal(report.completionProjectionStatus, "rejected");
  assert.doesNotMatch(JSON.stringify(report), /secret raw error/u);
});

test("oversized or truncated observations are bounded without declaring completion", () => {
  const input = fixture();
  input.result.evidence[0].value.padding = "x".repeat(260 * 1024);
  input.result.observations.push(...Array.from({ length: 130 }, () => ({ type: "irrelevant" })));
  const report = analyzeUnitPlaySkillEvidence(input);
  assert.equal(report.truncated, true);
  assert.equal(report.diagnosticCounts.evidence_size_limit, 1);
  assert.equal(report.completionProjectionStatus, "rejected");
});

test("server scope supports equipment observations without rewriting source time or accepting conflicts", () => {
  const input = fixture();
  const build = input.result.evidence.find((entry) => entry.toolName === "unit_builds");
  delete build.value.query.seasonContextId;
  assert.equal(analyzeUnitPlaySkillEvidence(input).equipmentStatisticsObserved, false);
  build.value.scope = { seasonContextId: season.id, patch: "17.9" };
  assert.equal(analyzeUnitPlaySkillEvidence(input).equipmentStatisticsObserved, true);
  build.value.query.seasonContextId = "set18-live";
  assert.equal(analyzeUnitPlaySkillEvidence(input).equipmentStatisticsObserved, false);
});

test("candidate official role coverage comes from exact scoped detail facts, never membership or ability inference", async () => {
  const input = fixture();
  input.skill = candidateSkill;
  input.runtimeAvailableTools = candidateSkill.allowedTools;
  input.selection = matchSkill(input.taskFrame, new SkillRegistry({ definitions: [candidateSkill], toolRegistry: registry }));
  const handler = createTftToolHandlers({ registry, seasonContext: season,
    loadOfficialEntityDetails: async () => ({ meta: { updatedAt: stamp }, units: new Map([[unitId, {
      name: "测试英雄", role: "Magic.Tank", cost: 2, ability: { name: "技能", description: "获得护盾。" }
    }]]) })
  }).handlers.unit_details;
  const value = await handler({ apiName: unitId });
  const ledger = new EvidenceLedger({ createId: () => "official-role", now: () => NOW });
  const definition = registry.get("unit_details");
  const { entry } = ledger.add({ definition, toolResult: { status: "completed", toolName: "unit_details", toolCallId: "role-call", value,
    metadata: { source: definition.source, evidenceType: definition.evidenceType, updatedAt: value.updatedAt, modelGeneratedStatistics: false } },
    evidenceContract: { source: definition.source, type: definition.evidenceType, requiredFields: ["source", "updatedAt"], allowModelGeneratedStatistics: false } });
  input.result.evidence.push(entry);
  input.result.evidenceIds.push(entry.evidenceId);
  input.result.observations.push({ type: "tool_result", status: "completed", tool: "unit_details", toolCallId: entry.toolCallId,
    evidenceId: entry.evidenceId, evidenceStatus: "valid", value });
  assert.ok(analyzeUnitPlaySkillEvidence(input).coveredFacets.includes("unit_role"));
  assert.equal(analyzeUnitPlaySkillEvidence(input).dataAvailability.official_unit_details, "available");
  for (const mutate of [
    (candidate) => { candidate.value.facts.role = null; },
    (candidate) => { candidate.value.apiName = "another"; },
    (candidate) => { candidate.value.scope.seasonContextId = "set18-live"; },
    (candidate) => { candidate.value.scope.patch = "17.8"; },
    (candidate) => { candidate.temporalStatus = "historical"; },
    (candidate) => { candidate.value.source.updatedAt = "2000-01-01T00:00:00Z"; }
  ]) {
    const candidate = { ...input, result: structuredClone(input.result) };
    mutate(candidate.result.evidence.find((item) => item.evidenceId === entry.evidenceId));
    assert.ok(!analyzeUnitPlaySkillEvidence(candidate).coveredFacets.includes("unit_role"));
  }
});

async function mechanismFixture() {
  const input = fixture();
  input.skill = mechanismSkill;
  input.runtimeAvailableTools = mechanismSkill.allowedTools;
  input.selection = matchSkill(input.taskFrame, new SkillRegistry({definitions:[mechanismSkill],toolRegistry:registry}));
  const itemIds = ["TFT_Item_InfinityEdge", "TFT_Item_SpearOfShojin", "TFT_Item_SteraksGage"];
  input.result.evidence.find(e=>e.toolName==="unit_builds").value.cards[0].items = itemIds.map(apiName=>({apiName}));
  const details = buildOfficialTftItemDetailsCatalog({season:"TFT17",version:"17.9",time:"2026-08-27T00:00:00Z",
    data:itemIds.map((apiName,i)=>({englishName:apiName,equipId:String(i+1),name:`装备${i+1}`,effect:"普攻提供法力回复。"}))},
    {retrieval:{schemaVersion:"official-item-retrieval.v1",transport:"http_success",fetchedAt:stamp,
      sourceId:"https://game.gtimg.cn/images/lol/act/img/tft/js/equip.js",contentHash:"a".repeat(64)}});
  const handlers = createTftToolHandlers({officialItemEvidenceV1:true,seasonContext:season,
    loadOfficialItemDetails:async()=>details}).handlers;
  for (const [index,apiName] of itemIds.entries()) {
    const value = await handlers.item_details({apiName});
    const definition = registry.get("item_details");
    const ledger = new EvidenceLedger({createId:()=>`official-item-${index}`,now:()=>NOW});
    const {entry} = ledger.add({definition,toolResult:{toolName:"item_details",toolCallId:`item-call-${index}`,status:"completed",value,
      metadata:{source:definition.source,evidenceType:definition.evidenceType,updatedAt:value.updatedAt,modelGeneratedStatistics:false}},
      evidenceContract:{source:definition.source,type:definition.evidenceType,requiredFields:["source","updatedAt"],allowModelGeneratedStatistics:false}});
    input.result.evidence.push(entry);
    input.result.evidenceIds.push(entry.evidenceId);
    input.result.observations.push({type:"tool_result",status:"completed",tool:"item_details",toolCallId:entry.toolCallId,
      evidenceId:entry.evidenceId,evidenceStatus:"valid",value});
  }
  return input;
}

test("v1.5 binds all leading build item effects but does not claim that the answer explained them", async () => {
  const input = await mechanismFixture();
  const before = JSON.stringify(input.result);
  const report = analyzeUnitPlaySkillEvidence(input);
  assert.ok(report.coveredFacets.includes("equipment_logic"));
  assert.equal(report.dataAvailability.official_item_details,"available");
  assert.equal(report.sourceStatements.filter(f=>f.facetId==="equipment_logic").length,3);
  assert.equal(report.answerCoverage.completionEvaluated,false);
  assert.ok(report.answerCoverage.unassessedFacets.includes("equipment_logic"));
  assert.equal(JSON.stringify(input.result),before);
  input.skill = candidateSkill;
  input.runtimeAvailableTools = candidateSkill.allowedTools;
  input.selection = matchSkill(input.taskFrame,new SkillRegistry({definitions:[candidateSkill],toolRegistry:registry}));
  assert.ok(!analyzeUnitPlaySkillEvidence(input).coveredFacets.includes("equipment_logic"),"frozen v1.4 unchanged");
});

test("server-planned item batch covers the same leading build mechanisms without individual detail calls", async () => {
  const input = await mechanismFixture();
  const detailEntries = input.result.evidence.filter((entry) => entry.toolName === "item_details");
  const detailValues = detailEntries.map((entry) => entry.value);
  const apiNames = detailValues.map((value) => value.apiName);
  input.result.evidence = input.result.evidence.filter((entry) => entry.toolName !== "item_details");
  input.result.observations = input.result.observations.filter((entry) => entry.tool !== "item_details");
  input.result.evidenceIds = input.result.evidenceIds.filter((id) => !detailEntries.some((entry) => entry.evidenceId === id));
  const value = { schemaVersion: "official-item-detail-batch.v1", type: "item_details_batch", status: "found",
    scope: detailValues[0].scope, selection: { strategy: "unit_play_leading_build", apiNames, maxItems: 4 },
    items: detailValues.map((item, index) => ({ ...item, claimId: `official-item:${item.apiName}`, evidencePath: `/items/${index}` })),
    mechanismStatus: "available", updatedAt: detailValues[0].updatedAt, warnings: [] };
  const definition = registry.get("item_details_batch");
  const ledger = new EvidenceLedger({ createId: () => "official-item-batch", now: () => NOW });
  const { entry } = ledger.add({ definition, toolResult: { toolName: "item_details_batch", toolCallId: "item-batch-call",
    status: "completed", value, metadata: { source: definition.source, evidenceType: definition.evidenceType,
      updatedAt: value.updatedAt, modelGeneratedStatistics: false } }, evidenceContract: { source: definition.source,
      type: definition.evidenceType, requiredFields: ["source", "updatedAt"], allowModelGeneratedStatistics: false } });
  input.result.evidence.push(entry);
  input.result.evidenceIds.push(entry.evidenceId);
  input.result.observations.push({ type: "tool_result", status: "completed", tool: "item_details_batch",
    toolCallId: entry.toolCallId, evidenceId: entry.evidenceId, evidenceStatus: "valid", value });
  input.skill = batchMechanismSkill;
  input.runtimeAvailableTools = batchMechanismSkill.allowedTools;
  input.selection = matchSkill(input.taskFrame, new SkillRegistry({ definitions: [batchMechanismSkill], toolRegistry: registry }));
  const report = analyzeUnitPlaySkillEvidence(input);
  assert.ok(report.coveredFacets.includes("equipment_logic"), JSON.stringify(report));
  assert.equal(report.sourceStatements.filter((fact) => fact.facetId === "equipment_logic").length, 3);
  assert.ok(report.sourceStatements.filter((fact) => fact.facetId === "equipment_logic")
    .every((fact) => fact.evidenceId === entry.evidenceId && fact.path.startsWith("items[")));
  const invalid = { ...input, result: structuredClone(input.result) };
  invalid.result.evidence.find((candidate) => candidate.evidenceId === entry.evidenceId).value.selection.apiNames.reverse();
  assert.ok(!analyzeUnitPlaySkillEvidence(invalid).coveredFacets.includes("equipment_logic"));
});

test("v1.5 cannot fill equipment logic with unrelated, partial, historical, unobserved or stale effects", async () => {
  const original = await mechanismFixture();
  for (const mutate of [
    input=>{input.result.evidence = input.result.evidence.filter(e=>e.toolName!=="unit_builds");},
    input=>{input.result.evidence.find(e=>e.toolName==="unit_builds").value.query.unit="another";},
    input=>{input.result.evidence.pop();},
    input=>{input.result.evidence.at(-1).value.apiName="another";},
    input=>{input.result.evidence.at(-1).value.facts.effect="";},
    input=>{input.result.evidence.at(-1).value.facts.numericFormulaComplete=false;},
    input=>{input.result.evidence.at(-1).value.facts.unresolvedTokens=["unknown"];},
    input=>{input.result.evidence.at(-1).temporalStatus="historical";},
    input=>{input.result.evidence.at(-1).value.source.retrieval.fetchedAt="2026-08-29T00:00:00Z";},
    input=>{input.result.evidence.at(-1).value.scope.patch="17.8";},
    input=>{input.result.observations.pop();}
  ]) {
    const input = {...original,result:structuredClone(original.result)};
    mutate(input);
    assert.ok(!analyzeUnitPlaySkillEvidence(input).coveredFacets.includes("equipment_logic"));
  }
});

test("answer-only candidate keeps mechanism binding and answer coverage separate, including failed sources", async () => {
  const original = await mechanismFixture();
  const baseline = analyzeUnitPlaySkillEvidence(original);
  const input = { ...original, skill: answerSkill, runtimeAvailableTools: answerSkill.allowedTools,
    selection: matchSkill(original.taskFrame, new SkillRegistry({ definitions: [answerSkill], toolRegistry: registry })) };
  const report = analyzeUnitPlaySkillEvidence(input);
  assert.deepEqual(report.coveredFacets, baseline.coveredFacets);
  assert.deepEqual(report.answerCoverage, baseline.answerCoverage);
  assert.equal(report.answerCoverage.completionEvaluated, false);
  for (const mutate of [
    result => { result.evidence.at(-1).value.source.retrieval.fetchedAt = "2026-08-29T00:00:00Z"; },
    result => { result.evidence.at(-1).value.facts.effect = ""; },
    result => { result.evidence = result.evidence.filter(entry => entry.toolName !== "item_details"); }
  ]) {
    const result = structuredClone(original.result);
    mutate(result);
    const failed = analyzeUnitPlaySkillEvidence({ ...input, result });
    assert.ok(!failed.coveredFacets.includes("equipment_logic"));
    assert.equal(failed.answerCoverage.completionEvaluated, false);
  }
});

test("compact answer candidate changes no Evidence or completion semantics", async () => {
  const original = await mechanismFixture();
  const reports = [answerSkill, compactAnswerSkill].map(skill => analyzeUnitPlaySkillEvidence({
    ...original, skill, runtimeAvailableTools: skill.allowedTools,
    selection: matchSkill(original.taskFrame, new SkillRegistry({ definitions: [skill], toolRegistry: registry }))
  }));
  assert.deepEqual(reports[1], reports[0]);
  assert.equal(reports[1].answerCoverage.completionEvaluated, false);
});

test("cards-only answer candidate narrows tools without changing Evidence or completion semantics", async () => {
  const original = await mechanismFixture();
  const reports = [compactAnswerSkill, cardsOnlyAnswerSkill, exactCardQuerySkill].map(skill => analyzeUnitPlaySkillEvidence({
    ...original, skill, runtimeAvailableTools: skill.allowedTools,
    selection: matchSkill(original.taskFrame, new SkillRegistry({ definitions: [skill], toolRegistry: registry }))
  }));
  for (const key of ["requiredFacets", "coveredFacets", "missingFacets", "unsupportedFacets",
    "completionProjectionStatus", "answerCoverage", "equipmentStatisticsObserved", "mappedFactCount", "sourceStatements"]) {
    assert.deepEqual(reports[1][key], reports[0][key], key);
    assert.deepEqual(reports[2][key], reports[0][key], `${key}:exact-query`);
  }
  assert.equal(reports[1].diagnosticCounts.tool_not_allowed, 1);
  assert.equal(reports[1].dataAvailability.mechanism_knowledge_index, "unavailable");
  assert.equal(reports[2].diagnosticCounts.tool_not_allowed, 1);
  assert.equal(reports[2].dataAvailability.mechanism_knowledge_index, "unavailable");
  assert.equal(cardsOnlyAnswerSkill.allowedTools.includes("semantic_search"), false);
  assert.equal(exactCardQuerySkill.allowedTools.includes("semantic_search"), false);
  assert.equal(reports[1].answerCoverage.completionEvaluated, false);
});
