CREATE TABLE IF NOT EXISTS schema_migrations (
  version text PRIMARY KEY,
  checksum text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS data_migration_batches (
  batch_id uuid PRIMARY KEY,
  source_type text NOT NULL,
  source_fingerprint text NOT NULL,
  status text NOT NULL,
  report_json jsonb,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  UNIQUE (source_type, source_fingerprint)
);

CREATE TABLE IF NOT EXISTS user_preferences (
  preference_key text PRIMARY KEY,
  value_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS entity_aliases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_context_id text NOT NULL,
  alias text NOT NULL,
  normalized_alias text NOT NULL,
  entity_type text NOT NULL,
  api_name text NOT NULL,
  confidence double precision NOT NULL DEFAULT 0.5 CHECK (confidence >= 0 AND confidence <= 1),
  source text NOT NULL,
  effective_patch text,
  enabled boolean NOT NULL DEFAULT true,
  updated_by text NOT NULL DEFAULT 'system',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_context_id, normalized_alias, entity_type, api_name, source)
);
CREATE INDEX IF NOT EXISTS entity_aliases_lookup_idx ON entity_aliases(season_context_id, normalized_alias, entity_type, enabled);

CREATE TABLE IF NOT EXISTS item_catalog (
  id uuid PRIMARY KEY,
  season_context_id text NOT NULL,
  provider text NOT NULL,
  provider_version text NOT NULL,
  external_id text NOT NULL,
  effective_patch text NOT NULL,
  region_or_platform text,
  queue text,
  zh_name text,
  category text NOT NULL,
  current boolean NOT NULL,
  obtainable boolean NOT NULL,
  aliases jsonb NOT NULL DEFAULT '[]'::jsonb,
  provider_metadata jsonb,
  fetched_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_context_id, provider, external_id)
);
CREATE INDEX IF NOT EXISTS item_catalog_patch_idx ON item_catalog(season_context_id, provider_version, effective_patch, category, current);

CREATE TABLE IF NOT EXISTS units (
  id uuid PRIMARY KEY,
  season_context_id text NOT NULL,
  provider text NOT NULL,
  provider_version text NOT NULL,
  external_id text NOT NULL,
  effective_patch text NOT NULL,
  region_or_platform text,
  queue text,
  zh_name text,
  aliases jsonb NOT NULL DEFAULT '[]'::jsonb,
  current boolean NOT NULL,
  provider_metadata jsonb,
  fetched_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_context_id, provider, external_id)
);
CREATE INDEX IF NOT EXISTS units_patch_idx ON units(season_context_id, provider_version, effective_patch, current);

CREATE TABLE IF NOT EXISTS traits (
  id uuid PRIMARY KEY,
  season_context_id text NOT NULL,
  provider text NOT NULL,
  provider_version text NOT NULL,
  external_id text NOT NULL,
  filter_id text NOT NULL,
  effective_patch text NOT NULL,
  region_or_platform text,
  queue text,
  zh_name text,
  display_name text,
  aliases jsonb NOT NULL DEFAULT '[]'::jsonb,
  current boolean NOT NULL,
  provider_metadata jsonb,
  fetched_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_context_id, provider, external_id),
  UNIQUE (season_context_id, provider, filter_id)
);
CREATE INDEX IF NOT EXISTS traits_patch_idx ON traits(season_context_id, provider_version, effective_patch, current);

CREATE TABLE IF NOT EXISTS query_events (
  query_id uuid PRIMARY KEY,
  run_id text,
  season_context_id text NOT NULL,
  visitor_scope text NOT NULL,
  conversation_id text,
  input text NOT NULL,
  result_type text,
  query_json jsonb,
  response_json jsonb,
  provider text,
  provider_version text,
  effective_patch text,
  region_or_platform text,
  queue text,
  fetched_at timestamptz,
  cache_hit boolean NOT NULL DEFAULT false,
  cache_stale boolean NOT NULL DEFAULT false,
  llm_used boolean NOT NULL DEFAULT false,
  llm_model text,
  duration_ms integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS query_events_visitor_idx ON query_events(season_context_id, visitor_scope, created_at);
CREATE INDEX IF NOT EXISTS query_events_created_idx ON query_events(created_at);

CREATE TABLE IF NOT EXISTS feedback_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feedback_id text NOT NULL UNIQUE,
  season_context_id text NOT NULL,
  query_id uuid REFERENCES query_events(query_id) ON DELETE SET NULL,
  visitor_scope text,
  feedback_target text,
  feedback_type text NOT NULL,
  rating text,
  card_index integer,
  reason text,
  payload_json jsonb NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS feedback_events_query_idx ON feedback_events(query_id);
CREATE INDEX IF NOT EXISTS feedback_events_created_idx ON feedback_events(created_at);

CREATE TABLE IF NOT EXISTS admin_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_context_id text NOT NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  before_json jsonb,
  after_json jsonb,
  actor text NOT NULL DEFAULT 'admin',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS admin_audit_scope_idx ON admin_audit_events(season_context_id, created_at);

CREATE TABLE IF NOT EXISTS comp_profiles (
  season_context_id text NOT NULL,
  profile_key text NOT NULL,
  difficulty integer,
  beginner_friendly integer,
  pivot_difficulty integer,
  position_difficulty integer,
  contest_tolerance integer,
  econ_difficulty integer,
  notes_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  enabled boolean NOT NULL DEFAULT true,
  source text NOT NULL DEFAULT 'admin',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (season_context_id, profile_key)
);

CREATE TABLE IF NOT EXISTS comp_profile_bindings (
  season_context_id text NOT NULL,
  profile_key text NOT NULL,
  provider text NOT NULL,
  provider_version text NOT NULL DEFAULT 'unknown',
  cluster_id text NOT NULL,
  lineup_signature text NOT NULL,
  signature_version text NOT NULL,
  strategy_override text,
  match_confidence double precision NOT NULL,
  match_status text NOT NULL,
  last_verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (season_context_id, profile_key, provider),
  FOREIGN KEY (season_context_id, profile_key) REFERENCES comp_profiles(season_context_id, profile_key) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS comp_profile_bindings_lookup_idx ON comp_profile_bindings(season_context_id, provider, cluster_id, lineup_signature, match_status);

CREATE TABLE IF NOT EXISTS comp_trend_history (
  season_context_id text NOT NULL,
  history_key text NOT NULL,
  provider text NOT NULL,
  provider_version text NOT NULL,
  effective_patch text NOT NULL,
  region_or_platform text,
  queue text,
  value_json jsonb NOT NULL,
  fetched_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (season_context_id, history_key)
);
