CREATE TABLE IF NOT EXISTS metatft_snapshot_batch (
  snapshot_batch_id uuid PRIMARY KEY,
  captured_at timestamptz NOT NULL,
  captured_date date NOT NULL,
  status text NOT NULL CHECK (status IN ('RUNNING','SUCCESS','PARTIAL','FAILED')),
  report_json jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz
);

CREATE TABLE IF NOT EXISTS metatft_comp_snapshot (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_batch_id uuid NOT NULL REFERENCES metatft_snapshot_batch(snapshot_batch_id),
  captured_at timestamptz NOT NULL,
  captured_date date NOT NULL,
  environment text NOT NULL CHECK (environment IN ('LIVE','PBE')),
  patch text,
  tft_set text NOT NULL,
  region text NOT NULL,
  cohort text NOT NULL,
  rank_filter text,
  rank_bucket_schema_version text,
  window_days smallint NOT NULL CHECK (window_days = 1),
  comp_key text NOT NULL,
  comp_key_version text NOT NULL,
  source_cluster_id text NOT NULL,
  comp_name text NOT NULL,
  games bigint NOT NULL CHECK (games >= 0),
  avg_placement double precision NOT NULL CHECK (avg_placement >= 1 AND avg_placement <= 8),
  top4_rate double precision NOT NULL CHECK (top4_rate >= 0 AND top4_rate <= 1),
  win_rate double precision NOT NULL CHECK (win_rate >= 0 AND win_rate <= 1),
  pick_rate double precision NOT NULL CHECK (pick_rate >= 0 AND pick_rate <= 1),
  selection_rate double precision NOT NULL CHECK (selection_rate >= 0 AND selection_rate <= 8),
  source text NOT NULL CHECK (source = 'metatft'),
  source_updated_at timestamptz,
  raw_payload_hash text NOT NULL,
  data_origin text NOT NULL CHECK (data_origin IN ('DIRECT','DERIVED')),
  units_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  traits_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS metatft_comp_snapshot_daily_unique
ON metatft_comp_snapshot(captured_date,environment,COALESCE(patch,''),region,cohort,window_days,comp_key);

CREATE INDEX IF NOT EXISTS metatft_comp_snapshot_history_idx
ON metatft_comp_snapshot(environment,cohort,comp_key,captured_date);
