// Verified against Riot English and Traditional Chinese 18.3 notes (2026-09-23).
// Official timestamp: 2026-09-22T18:00:00.000Z = September 23 02:00 Asia/Shanghai.
export const PATCH_18_3_REVISION = Object.freeze({
  id: "18.3-release-2026-09-23",
  publishedAt: "2026-09-23",
  kind: "release",
  title: {"zh-CN": "18.3 正式版本数值调整", "en-US": "18.3 release numeric changes"},
  summary: {"zh-CN": "共 74 项数值调整：强化部分重抽弈子与战斗强化符文，调整羁绊、神器、纹章和灵火。奈德丽穿透说明前后矛盾且标注无功能变化，未计入数值清单；完整机制与修复见官方原文。", "en-US": "74 numeric changes across champions, traits, Artifacts, Emblems, Augments, and Wisps. Conflicting Nidalee penetration notes marked no functional change are excluded; see the official article for rules and fixes."},
  groups: [
    { title: {"zh-CN": "羁绊：灵魂莲华强化灵火", "en-US": "Traits: Blossom-enhanced Wisps"}, changes: [
      {"id": "blossom-animate", "direction": "nerf", "before": "26s", "after": "24s", "text": {"zh-CN": "灵魂莲华 · 动态商店持续时间", "en-US": "Blossom · Animate Shop duration"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "animate_shop_duration"},
      {"id": "blossom-blaze", "direction": "nerf", "before": "1.5%", "after": "1.25%", "text": {"zh-CN": "灵魂莲华 · 烈炎最大生命值伤害", "en-US": "Blossom · Blaze max-Health damage"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "blaze_damage"},
      {"id": "blossom-blood-money", "direction": "nerf", "before": "1g", "after": "2g", "text": {"zh-CN": "灵魂莲华 · 血汗钱价格", "en-US": "Blossom · Blood Money cost"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "blood_money_cost"},
      {"id": "blossom-combust", "direction": "nerf", "before": "22%", "after": "18%", "text": {"zh-CN": "灵魂莲华 · 爆发四散伤害", "en-US": "Blossom · Combust damage"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "combust_damage"},
      {"id": "blossom-curio", "direction": "nerf", "before": "2g", "after": "1g", "text": {"zh-CN": "灵魂莲华 · 珍品购物车额外金币", "en-US": "Blossom · Curio Cart bonus gold"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "curio_bonus_gold"},
      {"id": "blossom-rivalry", "direction": "mixed", "before": "7", "after": "5", "text": {"zh-CN": "灵魂莲华 · 激烈对决参与击杀数（原文 Takedowns）", "en-US": "Blossom · Heated Rivalry takedowns"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "heated_rivalry_takedowns"},
      {"id": "blossom-sacrifice-ad-ap", "direction": "nerf", "before": "40%", "after": "35%", "text": {"zh-CN": "灵魂莲华 · 英勇牺牲攻击力 / 法强", "en-US": "Blossom · Heroic Sacrifice AD / AP"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "heroic_sacrifice_ad_ap"},
      {"id": "blossom-sacrifice-resists", "direction": "nerf", "before": "40", "after": "35", "text": {"zh-CN": "灵魂莲华 · 英勇牺牲护甲 / 魔抗", "en-US": "Blossom · Heroic Sacrifice resists"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "heroic_sacrifice_resists"},
      {"id": "blossom-hugify", "direction": "nerf", "before": "600", "after": "500", "text": {"zh-CN": "灵魂莲华 · 巨大化生命值", "en-US": "Blossom · Hugify health"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "hugify_health"},
      {"id": "blossom-soil", "direction": "nerf", "before": "25%", "after": "20%", "text": {"zh-CN": "灵魂莲华 · 魔力土壤法力减免", "en-US": "Blossom · Mana-Rich Soil reduction"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "mana_rich_soil_reduction"},
      {"id": "blossom-mercenary", "direction": "nerf", "before": "4.5%", "after": "4%", "text": {"zh-CN": "灵魂莲华 · 佣兵部队伤害增幅", "en-US": "Blossom · Mercenary Force damage amp"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "mercenary_damage_amp"},
      {"id": "blossom-moonlight", "direction": "nerf", "before": "2g", "after": "3g", "text": {"zh-CN": "灵魂莲华 · 月光仪式价格", "en-US": "Blossom · Moonlight Ritual cost"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "moonlight_cost"},
      {"id": "blossom-sinister-gold", "direction": "nerf", "before": "3g", "after": "2g", "text": {"zh-CN": "灵魂莲华 · 邪恶交易金币", "en-US": "Blossom · Sinister Deal gold"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "sinister_gold"},
      {"id": "blossom-sinister-health", "direction": "buff", "before": "3", "after": "2", "text": {"zh-CN": "灵魂莲华 · 邪恶交易损失生命值", "en-US": "Blossom · Sinister Deal health lost"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "sinister_health_lost"},
      {"id": "blossom-stand-alone", "direction": "nerf", "before": "22%", "after": "20%", "text": {"zh-CN": "灵魂莲华 · 一夫当关生命值 / 伤害增幅", "en-US": "Blossom · Stand Alone health / damage amp"}, "entityType": "trait", "entityApiNames": ["DA_18_Blossom"], "stat": "stand_alone_health_damage_amp"},
    ] },
    { title: {"zh-CN": "其他羁绊", "en-US": "Other traits"}, changes: [
      {"id": "coven-essence", "direction": "buff", "before": "18/25/32/60", "after": "22/28/35/60", "text": {"zh-CN": "魔女 · 每次战败精华", "en-US": "Coven · Essence per loss"}, "entityType": "trait", "entityApiNames": ["DA_18_Coven"], "stat": "essence_per_loss"},
      {"id": "defender-resists", "direction": "nerf", "before": "25/60/120", "after": "25/60/115", "text": {"zh-CN": "护卫 · 护甲 / 魔抗", "en-US": "Defender · Resists"}, "entityType": "trait", "entityApiNames": ["DA_18_Defender"], "stat": "resists"},
      {"id": "hunter-ad", "direction": "nerf", "before": "20/30/45/65%", "after": "20/30/40/60%", "text": {"zh-CN": "猎人 · 额外攻击力", "en-US": "Hunter · Bonus AD"}, "entityType": "trait", "entityApiNames": ["DA_18_Hunter"], "stat": "bonus_ad"},
      {"id": "inferno-burn", "direction": "nerf", "before": "1/1/3.5/4.5%", "after": "1/1/3/4%", "text": {"zh-CN": "地狱火 · 灼烧比例", "en-US": "Inferno · Burn amount"}, "entityType": "trait", "entityApiNames": ["DA_18_Inferno"], "stat": "burn_amount"},
      {"id": "invoker-mana", "direction": "nerf", "before": "3/4/6/9", "after": "3/4/6/8", "text": {"zh-CN": "神谕 · 法力回复", "en-US": "Invoker · Mana regen"}, "entityType": "trait", "entityApiNames": ["DA_18_Invoker"], "stat": "mana_regen"},
    ] },
    { title: {"zh-CN": "一费弈子", "en-US": "Tier 1 champions"}, changes: [
      {"id": "karma-explosion", "direction": "buff", "before": "120/180/270/460%", "after": "125/185/300/515%", "text": {"zh-CN": "卡尔玛 · 爆炸伤害法强倍率", "en-US": "Karma · Explosion AP ratio"}, "entityType": "unit", "entityApiNames": ["DA_Karma18"], "stat": "explosion_ap_ratio"},
      {"id": "ornn-three-forge", "direction": "nerf", "before": "100%", "after": "85%", "text": {"zh-CN": "三星奥恩 · 锻造能量加成", "en-US": "Three-star Ornn · Forge Power bonus"}, "entityType": "unit", "entityApiNames": ["DA_18_Ornn"], "stat": "three_star_forge_bonus"},
      {"id": "ornn-second-artifact", "direction": "buff", "before": "155000", "after": "140000", "text": {"zh-CN": "奥恩 · 第二件神器锻造能量门槛", "en-US": "Ornn · Second Artifact Forge Power threshold"}, "entityType": "unit", "entityApiNames": ["DA_18_Ornn"], "stat": "second_artifact_threshold"},
      {"id": "veigar-ap-kill", "direction": "nerf", "before": "3%", "after": "2%", "text": {"zh-CN": "维迦 · 每次击杀获得法强", "en-US": "Veigar · AP per kill"}, "entityType": "unit", "entityApiNames": ["DA_18_Veigar"], "stat": "ap_per_kill"},
      {"id": "veigar-base", "direction": "buff", "before": "175/265/395/670%", "after": "200/300/450/765%", "text": {"zh-CN": "维迦 · 基础技能法强倍率", "en-US": "Veigar · Base ability AP ratio"}, "entityType": "unit", "entityApiNames": ["DA_18_Veigar"], "stat": "base_ability_ap_ratio"},
      {"id": "veigar-empowered", "direction": "buff", "before": "265/400/595/1015%", "after": "300/450/675/1015%", "text": {"zh-CN": "维迦 · 强化技能法强倍率", "en-US": "Veigar · Empowered ability AP ratio"}, "entityType": "unit", "entityApiNames": ["DA_18_Veigar"], "stat": "empowered_ability_ap_ratio"},
    ] },
    { title: {"zh-CN": "二费弈子", "en-US": "Tier 2 champions"}, changes: [
      {"id": "alistar-heal", "direction": "buff", "before": "200/260/320%", "after": "230/300/400%", "text": {"zh-CN": "阿利斯塔 · 治疗法强倍率", "en-US": "Alistar · Healing AP ratio"}, "entityType": "unit", "entityApiNames": ["DA_18_Alistar"], "stat": "healing_ap_ratio"},
      {"id": "alistar-damage", "direction": "buff", "before": "100/150/225%", "after": "180/270/420%", "text": {"zh-CN": "阿利斯塔 · 技能法强倍率", "en-US": "Alistar · Ability AP ratio"}, "entityType": "unit", "entityApiNames": ["DA_18_Alistar"], "stat": "ability_ap_ratio"},
      {"id": "gromp-ap-dot", "direction": "buff", "before": "160/240/360%", "after": "175/265/410%", "text": {"zh-CN": "魔沼蛙（法系）· 持续伤害法强倍率", "en-US": "Gromp AP form · DoT AP ratio"}, "entityType": "unit", "entityApiNames": ["DA_Gromp18_AP"], "stat": "dot_ap_ratio"},
      {"id": "gromp-ad-speed", "direction": "buff", "before": "0.7", "after": "0.75", "text": {"zh-CN": "魔沼蛙（物理）· 攻速", "en-US": "Gromp AD form · Attack speed"}, "entityType": "unit", "entityApiNames": ["DA_Gromp18_AD"], "stat": "base_attack_speed"},
      {"id": "gromp-ad", "direction": "buff", "before": "45", "after": "50", "text": {"zh-CN": "魔沼蛙（物理）· 基础攻击力", "en-US": "Gromp AD form · Base AD"}, "entityType": "unit", "entityApiNames": ["DA_Gromp18_AD"], "stat": "base_ad"},
      {"id": "murkwolf-damage", "direction": "buff", "before": "60/90/135%", "after": "65/100/160%", "text": {"zh-CN": "暗影狼 · 强化攻击攻击力倍率", "en-US": "Murkwolf · Empowered attack AD ratio"}, "entityType": "unit", "entityApiNames": ["DA_Murkwolf18"], "stat": "empowered_attack_ad_ratio"},
      {"id": "warwick-damage", "direction": "buff", "before": "215/325/500%", "after": "230/345/535%", "text": {"zh-CN": "沃里克 · 技能攻击力倍率", "en-US": "Warwick · Ability AD ratio"}, "entityType": "unit", "entityApiNames": ["DA_18_Warwick"], "stat": "ability_ad_ratio"},
      {"id": "warwick-healing", "direction": "buff", "before": "20%", "after": "25%", "text": {"zh-CN": "沃里克 · 技能治疗比例", "en-US": "Warwick · Ability healing"}, "entityType": "unit", "entityApiNames": ["DA_18_Warwick"], "stat": "ability_healing"},
    ] },
    { title: {"zh-CN": "三费弈子", "en-US": "Tier 3 champions"}, changes: [
      {"id": "azir-damage", "direction": "buff", "before": "43/65/103", "after": "46/69/110", "text": {"zh-CN": "阿兹尔 · 技能伤害", "en-US": "Azir · Ability damage"}, "entityType": "unit", "entityApiNames": ["DA_18_Azir"], "stat": "ability_damage"},
      {"id": "cassiopeia-damage", "direction": "buff", "before": "400/600/950", "after": "425/630/1020", "text": {"zh-CN": "卡西奥佩娅 · 技能伤害", "en-US": "Cassiopeia · Ability damage"}, "entityType": "unit", "entityApiNames": ["DA_18_Cassiopeia"], "stat": "ability_damage"},
      {"id": "rammus-shield", "direction": "buff", "before": "350/450/550", "after": "400/550/725", "text": {"zh-CN": "拉莫斯 · 护盾", "en-US": "Rammus · Shield"}, "entityType": "unit", "entityApiNames": ["DA_18_Rammus"], "stat": "shield"},
    ] },
    { title: {"zh-CN": "四费弈子", "en-US": "Tier 4 champions"}, changes: [
      {"id": "lillia-heal", "direction": "buff", "before": "325/475%", "after": "350/525%", "text": {"zh-CN": "莉莉娅 · 治疗法强倍率", "en-US": "Lillia · Healing AP ratio"}, "entityType": "unit", "entityApiNames": ["DA_18_Lillia"], "stat": "healing_ap_ratio"},
      {"id": "nidalee-ad-damage", "direction": "nerf", "before": "225/340%", "after": "210/315%", "text": {"zh-CN": "奈德丽（物理）· 技能攻击力倍率", "en-US": "Nidalee AD form · Ability AD ratio"}, "entityType": "unit", "entityApiNames": ["DA_Nidalee18_AD"], "stat": "ability_ad_ratio"},
      {"id": "nidalee-ap-third", "direction": "buff", "before": "300/450%", "after": "330/500%", "text": {"zh-CN": "奈德丽（法系）· 第三次攻击法强倍率", "en-US": "Nidalee AP form · Third attack AP ratio"}, "entityType": "unit", "entityApiNames": ["DA_Nidalee18_AP"], "stat": "third_attack_ap_ratio"},
    ] },
    { title: {"zh-CN": "五费弈子", "en-US": "Tier 5 champions"}, changes: [
      {"id": "lux-solar-bonus", "direction": "buff", "before": "12%", "after": "15%", "text": {"zh-CN": "日蚀骑士拉克丝 · 每名三星弈子额外伤害", "en-US": "Solar Lux · Bonus damage per three-star"}, "entityType": "unit", "entityApiNames": ["DA_Lux18_Base"], "stat": "solar_bonus_per_three_star"},
      {"id": "taric-shield", "direction": "nerf", "before": "100/225", "after": "75/150", "text": {"zh-CN": "塔里克 · 被动护盾基础值", "en-US": "Taric · Passive shield base"}, "entityType": "unit", "entityApiNames": ["DA_Taric18"], "stat": "passive_shield_base"},
      {"id": "taric-heal", "direction": "buff", "before": "250/375%", "after": "275/450%", "text": {"zh-CN": "塔里克 · 治疗法强倍率", "en-US": "Taric · Healing AP ratio"}, "entityType": "unit", "entityApiNames": ["DA_Taric18"], "stat": "healing_ap_ratio"},
    ] },
    { title: {"zh-CN": "神器", "en-US": "Artifacts"}, changes: [
      {"id": "collector-ad", "direction": "nerf", "before": "40%", "after": "35%", "text": {"zh-CN": "金币收集者 · 攻击力", "en-US": "The Collector · AD"}, "entityType": "item", "entityApiNames": ["TFT4_Item_OrnnTheCollector"], "stat": "attack_damage"},
      {"id": "eternal-pact-mana", "direction": "nerf", "before": "15", "after": "10", "text": {"zh-CN": "永恒契约 · 坦克施法时回复法力", "en-US": "Eternal Pact · Mana on tank cast"}, "entityType": "item", "entityApiNames": ["TFT_Item_Artifact_EternalPact"], "stat": "mana_on_tank_cast"},
      {"id": "statikk-ap", "direction": "buff", "before": "15%", "after": "25%", "text": {"zh-CN": "斯塔缇克电刃（神器）· 基础法强", "en-US": "Statikk Shiv (Artifact) · Base AP"}, "entityType": "item", "entityApiNames": ["TFT_Item_Artifact_StatikkShiv"], "stat": "base_ap"},
    ] },
    { title: {"zh-CN": "纹章", "en-US": "Emblems"}, changes: [
      {"id": "brawler-emblem-damage", "direction": "buff", "before": "2%", "after": "2.5%", "text": {"zh-CN": "斗士纹章 · 最大生命值伤害", "en-US": "Brawler Emblem · Max-Health damage"}, "entityType": "item", "entityApiNames": ["DA_18_EmblemBrawler"], "stat": "max_health_damage"},
      {"id": "hunter-emblem-ad", "direction": "nerf", "before": "18%", "after": "15%", "text": {"zh-CN": "猎人纹章 · 参与击杀获得攻击力", "en-US": "Hunter Emblem · AD per takedown"}, "entityType": "item", "entityApiNames": ["DA_18_EmblemHunter"], "stat": "ad_per_takedown"},
      {"id": "invoker-emblem-mana", "direction": "nerf", "before": "3", "after": "2", "text": {"zh-CN": "神谕纹章 · 法力回复", "en-US": "Invoker Emblem · Mana regen"}, "entityType": "item", "entityApiNames": ["DA_18_EmblemInvoker"], "stat": "mana_regen"},
      {"id": "juggernaut-emblem-mana", "direction": "nerf", "before": "15", "after": "10", "text": {"zh-CN": "主宰纹章 · 死亡时回复法力", "en-US": "Juggernaut Emblem · Mana restored on death"}, "entityType": "item", "entityApiNames": ["DA_18_EmblemJuggernaut"], "stat": "mana_on_death"},
    ] },
    { title: {"zh-CN": "强化符文", "en-US": "Augments"}, changes: [
      {"id": "blossoms-call-first", "direction": "buff", "before": "15/6/4/0g", "after": "15/5/3/0g", "text": {"zh-CN": "繁花召唤（Blossom’s Call）· 四费灵火门槛第一组", "en-US": "Blossom’s Call · Four-cost Wisp threshold, first row"}, "entityType": "augment", "entityApiNames": [], "stat": "four_cost_threshold_first_row"},
      {"id": "blossoms-call-second", "direction": "buff", "before": "X/15/8/5/0", "after": "X/15/8/4/0", "text": {"zh-CN": "繁花召唤（Blossom’s Call）· 第二组门槛（官方亦标四费）", "en-US": "Blossom’s Call · Second threshold row (also labeled four-cost by Riot)"}, "entityType": "augment", "entityApiNames": [], "stat": "threshold_second_row"},
      {"id": "challengers-grace", "direction": "buff", "before": "3s", "after": "4s", "text": {"zh-CN": "挑战者恩惠（Challenger’s Grace）· 增益持续时间", "en-US": "Challenger’s Grace · Buff duration"}, "entityType": "augment", "entityApiNames": [], "stat": "buff_duration"},
      {"id": "early-learnings", "direction": "nerf", "before": "5%", "after": "3%", "text": {"zh-CN": "早期教育（Early Learnings）· 基础攻击力 / 法强", "en-US": "Early Learnings · Baseline AD / AP"}, "entityType": "augment", "entityApiNames": [], "stat": "baseline_ad_ap"},
      {"id": "electrocharge", "direction": "nerf", "before": "30/50/70/90", "after": "25/40/60/80", "text": {"zh-CN": "电火花 I（Electrocharge I）· 各阶段伤害", "en-US": "Electrocharge I · Damage by stage"}, "entityType": "augment", "entityApiNames": [], "stat": "damage_by_stage"},
      {"id": "item-extraction", "direction": "nerf", "before": "4", "after": "3", "text": {"zh-CN": "装备萃取（Item Extraction）· 萃取次数（另补偿阿兹尔）", "en-US": "Item Extraction · Extractions (also grants an Azir)"}, "entityType": "augment", "entityApiNames": [], "stat": "extractions"},
      {"id": "future-focused", "direction": "nerf", "before": "8", "after": "5", "text": {"zh-CN": "着眼未来（Future Focused）· 金币", "en-US": "Future Focused · Gold"}, "entityType": "augment", "entityApiNames": [], "stat": "gold"},
      {"id": "giant-mighty", "direction": "buff", "before": "200", "after": "225", "text": {"zh-CN": "巨大强悍（Giant and Mighty）· 生命值", "en-US": "Giant and Mighty · Health"}, "entityType": "augment", "entityApiNames": [], "stat": "health"},
      {"id": "group-hug-one", "direction": "buff", "before": "6", "after": "7", "text": {"zh-CN": "抱团取暖 I（Group Hug I）· 双抗", "en-US": "Group Hug I · Resists"}, "entityType": "augment", "entityApiNames": [], "stat": "resists"},
      {"id": "group-hug-two", "direction": "buff", "before": "9", "after": "10", "text": {"zh-CN": "抱团取暖 II（Group Hug II）· 双抗", "en-US": "Group Hug II · Resists"}, "entityType": "augment", "entityApiNames": [], "stat": "resists"},
      {"id": "heroic-grab-bag", "direction": "buff", "before": "4g", "after": "6g", "text": {"zh-CN": "英雄礼包（Heroic Grab Bag）· 初始金币", "en-US": "Heroic Grab Bag · Initial gold"}, "entityType": "augment", "entityApiNames": [], "stat": "initial_gold"},
      {"id": "hold-line-ad", "direction": "buff", "before": "9%", "after": "11%", "text": {"zh-CN": "坚守前线（Hold the Line）· 攻击力", "en-US": "Hold the Line · AD"}, "entityType": "augment", "entityApiNames": [], "stat": "attack_damage"},
      {"id": "hold-line-ap", "direction": "buff", "before": "10%", "after": "11%", "text": {"zh-CN": "坚守前线（Hold the Line）· 法强", "en-US": "Hold the Line · AP"}, "entityType": "augment", "entityApiNames": [], "stat": "ability_power"},
      {"id": "jeweled-lotus", "direction": "buff", "before": "10%", "after": "15%", "text": {"zh-CN": "珠光莲花 I（Jeweled Lotus I）· 暴击率", "en-US": "Jeweled Lotus I · Crit chance"}, "entityType": "augment", "entityApiNames": [], "stat": "crit_chance"},
      {"id": "retribution", "direction": "nerf", "before": "25%", "after": "15%", "text": {"zh-CN": "报应（Retribution）· 暴击率", "en-US": "Retribution · Crit chance"}, "entityType": "augment", "entityApiNames": [], "stat": "crit_chance"},
      {"id": "shimmerscale-essence", "direction": "buff", "before": "8", "after": "6", "text": {"zh-CN": "金鳞精粹（Shimmerscale Essence）· 等待回合", "en-US": "Shimmerscale Essence · Round delay"}, "entityType": "augment", "entityApiNames": [], "stat": "round_delay"},
      {"id": "spirit-redemption", "direction": "buff", "before": "7.5%", "after": "9%", "text": {"zh-CN": "救赎之灵（Spirit of Redemption）· 治疗", "en-US": "Spirit of Redemption · Healing"}, "entityType": "augment", "entityApiNames": [], "stat": "healing"},
      {"id": "upward-mobility", "direction": "buff", "before": "1", "after": "2", "text": {"zh-CN": "向上流动（Upward Mobility）· 升级刷新次数", "en-US": "Upward Mobility · Rerolls on level"}, "entityType": "augment", "entityApiNames": [], "stat": "rerolls_on_level"},
    ] },
    { title: {"zh-CN": "普通灵火", "en-US": "Ordinary Wisps"}, changes: [
      {"id": "stat-boosters-resists", "direction": "nerf", "before": "10", "after": "8", "text": {"zh-CN": "属性强化器（Stat Boosters）· 护甲 / 魔抗", "en-US": "Stat Boosters · Armor / MR"}, "entityType": "system", "entityApiNames": [], "stat": "resists"},
      {"id": "stat-boosters-speed", "direction": "nerf", "before": "8%", "after": "6%", "text": {"zh-CN": "属性强化器（Stat Boosters）· 攻速", "en-US": "Stat Boosters · Attack speed"}, "entityType": "system", "entityApiNames": [], "stat": "attack_speed"},
      {"id": "blood-iron-cost", "direction": "nerf", "before": "3g", "after": "4g", "text": {"zh-CN": "鲜血与钢铁（Blood and Iron）· 价格", "en-US": "Blood and Iron · Cost"}, "entityType": "system", "entityApiNames": [], "stat": "cost"},
      {"id": "combust-damage", "direction": "nerf", "before": "18%", "after": "15%", "text": {"zh-CN": "爆发四散（Combust）· 爆炸伤害", "en-US": "Combust · Explosion damage"}, "entityType": "system", "entityApiNames": [], "stat": "explosion_damage"},
      {"id": "mana-soil-reduction", "direction": "nerf", "before": "18%", "after": "15%", "text": {"zh-CN": "魔力土壤（Mana-Rich Soil）· 法力减免", "en-US": "Mana-Rich Soil · Mana reduction"}, "entityType": "system", "entityApiNames": [], "stat": "mana_reduction"},
      {"id": "three-me-cost", "direction": "nerf", "before": "9g", "after": "10g", "text": {"zh-CN": "三个我（Three Me）· 价格", "en-US": "Three Me · Cost"}, "entityType": "system", "entityApiNames": [], "stat": "cost"},
    ] },
  ]
});
